<Project>
	<PropertyGroup>
		<PackageOutputPath>$(MSBuildThisFileDirectory)/.build/NuGet/</PackageOutputPath>
		<Authors>idenardi</Authors>
		<Owners>idenardi</Owners>
		<Copyright>Copyright © Ivan Denardi. Based on the original work by Jonathan Dick (Redth).</Copyright>
		<PackageProjectUrl>https://github.com/idenardi/Maui.GoogleMobileAds.iOS</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/idenardi/Maui.GoogleMobileAds.iOS</RepositoryUrl>
		<AssemblyFileVersion>$(PackageVersion)</AssemblyFileVersion>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' Or '$(TF_BUILD)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
</Project>